### ISSUE TITLE
[Feature] 原版的几个不合理设计（Docker、API接口、S3）

### ISSUE THREAD

**Issue by gowy222** [OpenListTeam/OpenList#74]
关于Docker使用方式标准化，API接口变更，用户UpSert接口，S3兼容性和必要性。

1. 支持环境变量配置Docker中部分参数如用户信息不通过自动生成而是读取环境变量等。
在不需要持久卷的使用场景，环境变量更容易迁移服务器部署
一套helm配置文件,多个节点可以确保一致性

2. API接口，一旦固定，不要随意改变
/api/admin/storage/create
/api/admin/storage/update
这两个接口不够需要增加语义化upsert接口
并规范各API接口统一性

3. 支持并发请求三方网盘拉平tree结构，不通过缓存等直接请求对应文件。并考虑拉取速率。

And see https://github.com/OpenListTeam/OpenList/issues/74#issuecomment-2973235964

**Comment by arkimium** [comment]
测试过，给人感觉有点困惑。（看到这个issue后去docker desktop看了下还真有）
当然目前有关Docker用法的文档还没重构，先看看吧，因为docker镜像目前才发行beta版。

![Image](https://github.com/user-attachments/assets/e7b2537b-85cc-47b7-8fe1-9725fb9d10f7)

![Image](https://github.com/user-attachments/assets/959915a1-f24d-4a86-aacc-de907fa8cebe)

**Comment by TwoOnefour** [comment]
话糙理不糙

**Comment by xrgzs** [comment]
Issues raised by gowy222 was labeled as `wontfix` or `not planned` by xhofe:

- https://github.com/AlistGo/alist/issues/1366
- https://github.com/AlistGo/alist/issues/1376
- https://github.com/AlistGo/alist/issues/2380
- https://github.com/AlistGo/alist/issues/3029
- https://github.com/AlistGo/alist/issues/3143
- https://github.com/AlistGo/alist/issues/3701
- https://github.com/AlistGo/alist/issues/5337

**Comment by arkimium** [comment]
好的，等我周六再调试看看。

**Comment by gowy222** [comment]
> Issues raised by gowy222 was labeled as `wontfix` or `not planned` by xhofe:
> 
> * [建议加个webdav异常推送功能，比如阿里盘不能工作了，需要手动来重新换token或者干嘛，推送到指定配置里的url_callback AlistGo/alist#1366](https://github.com/AlistGo/alist/issues/1366)
> * [189能不能加个手机app的协议? 只有手机app会员多了两个功能: 在线解压+同步盘内部迅雷离线下载 AlistGo/alist#1376](https://github.com/AlistGo/alist/issues/1376)
> * [V3 全局 设置->站点 ->默认每页数量30 不起作用, list刷新 per_page 还是= 0, 近1W子文件夹 载入直接卡崩  AlistGo/alist#2380](https://github.com/AlistGo/alist/issues/2380)
> * [V3 - 189 文件夹 内部3W多个子文件夹...刷新一次好卡... 而list这个api后台审计调用,其实不需要缓存和走alist内部sql AlistGo/alist#3029](https://github.com/AlistGo/alist/issues/3029)
> * [v3.9.1 docker-compose 部署，备份和恢复有点坑... 全新安装,Alist自己的备份自己恢复报错... AlistGo/alist#3143](https://github.com/AlistGo/alist/issues/3143)
> * [K8S 本地持久卷 pv+pvc 映射 /opt/alist/data  导致 ./alist admin 报错..无法读取env.. AlistGo/alist#3701](https://github.com/AlistGo/alist/issues/3701)
> * [概率BUG ./alist admin set 时机太快和alist初始化设置随机账密冲突？db还没准备好？能不能支持下容器参数直接指定admin账密？ AlistGo/alist#5337](https://github.com/AlistGo/alist/issues/5337)

好尬....原来提过这么多....

**Comment by jyxjjj** [comment]
> 关于2

但Breaking Features确实是会存在的，团队后期可能会通过版本号来提示兼容性等，也会考虑你的建议。

无论可能会更贴近Restful或更贴近语义化，create update upsert均会是三个接口。
大致方案如Restful 下 POST创建，PATCH更新，PUT不存在则创建/存在则更新。
后期可能会在这两个方向中进行选择。


> 关于3

我本人目前认为这个是个人使用问题，可能会有一些其他用户需要这样的行为和使用方式。会考虑通过设置上限等方式进行调整。

> 关于1

我们可以先确认加入后期工作中，但具体什么时候可用请耐心关注。另外因为我个人比较喜欢Podman，确实您说的情况更符合正确使用方式，且基于Pods更方便普通用户实现真正的一键化，我也会推动成员们进行积极探索。感谢您的支持。

---

我将修改且可能多次修改您的意见内容，使其更符合社区规则，并更容易让成员理解。

**Comment by jyxjjj** [comment]
And see #76

**Comment by gowy222** [comment]
> > 关于2
> 
> 但Breaking Features确实是会存在的，团队后期可能会通过版本号来提示兼容性等，也会考虑你的建议。
> 
> 无论可能会更贴近Restful或更贴近语义化，create update upsert均会是三个接口。 大致方案如Restful 下 POST创建，PATCH更新，PUT不存在则创建/存在则更新。 后期可能会在这两个方向中进行选择。
> 
> > 关于3
> 
> 我本人目前认为这个是个人使用问题，可能会有一些其他用户需要这样的行为和使用方式。会考虑通过设置上限等方式进行调整。
> 
> > 关于1
> 
> 我们可以先确认加入后期工作中，但具体什么时候可用请耐心关注。另外因为我个人比较喜欢Podman，确实您说的情况更符合正确使用方式，且基于Pods更方便普通用户实现真正的一键化，我也会推动成员们进行积极探索。感谢您的支持。
> 
> 我将修改且可能多次修改您的意见内容，使其更符合社区规则，并更容易让成员理解。

感谢，再提个建议，https://github.com/tursodatabase/limbo  rust版本多线程 sqlite 内置数据平替... 也加入考虑下!

**Comment by jyxjjj** [comment]
> 感谢，再提个建议，https://github.com/tursodatabase/limbo rust版本多线程 sqlite 内置数据平替... 也加入考虑下!

这需要 命令行、FFI 或者RPC 应该不会考虑 如果有数据性能问题可以直接切换到MySQL、MariaDB等。目前原版也是支持的。

**Comment by thshu** [comment]
直接用docker环境变量的话不能放敏感信息，不然其他的docker服务如果有权限是可以读取到的，会出现泄漏的问题

**Comment by gowy222** [comment]
> 直接用docker环境变量的话不能放敏感信息，不然其他的docker服务如果有权限是可以读取到的，会出现泄漏的问题

这是用户侧的风险，不涉及openlist本身职责。业务容器可以全部走rootless

**Comment by thshu** [comment]
> > 直接用docker环境变量的话不能放敏感信息，不然其他的docker服务如果有权限是可以读取到的，会出现泄漏的问题
> 
> 这是用户侧的风险，不涉及openlist本身职责。业务容器可以全部走rootless

这样肯定不行，就好像你给了一个选择，但是这个选择是有问题的，泄漏了又会有很多麻烦

**Comment by gowy222** [comment]
> > > 直接用docker环境变量的话不能放敏感信息，不然其他的docker服务如果有权限是可以读取到的，会出现泄漏的问题
> > 
> > 
> > 这是用户侧的风险，不涉及openlist本身职责。业务容器可以全部走rootless
> 
> 这样肯定不行，就好像你给了一个选择，但是这个选择是有问题的，泄漏了又会有很多麻烦

你要这么讲，mysql岂不是都不能用docker部署了？

**Comment by ILoveScratch2** [comment]
> 直接用docker环境变量的话不能放敏感信息，不然其他的docker服务如果有权限是可以读取到的，会出现泄漏的问题


依然可以

我的docker是隔离的，镜像互相读不到

而且用户怎么选择是他们的自由

**Comment by ILoveScratch2** [comment]
> > > 直接用docker环境变量的话不能放敏感信息，不然其他的docker服务如果有权限是可以读取到的，会出现泄漏的问题
> > 
> > 这是用户侧的风险，不涉及openlist本身职责。业务容器可以全部走rootless
> 
> 这样肯定不行，就好像你给了一个选择，但是这个选择是有问题的，泄漏了又会有很多麻烦


那都是配置错误，比如指定文件env什么的

正确使用不会泄露

**Comment by ILoveScratch2** [comment]
> > > 直接用docker环境变量的话不能放敏感信息，不然其他的docker服务如果有权限是可以读取到的，会出现泄漏的问题
> > 
> > 这是用户侧的风险，不涉及openlist本身职责。业务容器可以全部走rootless
> 
> 这样肯定不行，就好像你给了一个选择，但是这个选择是有问题的，泄漏了又会有很多麻烦

按照你的说法，那现在的logs输出密码也不安全啊

**Comment by ILoveScratch2** [comment]
> 关于Docker使用方式标准化，API接口变更，用户UpSert接口，S3兼容性和必要性。
> 
> 1. 支持环境变量配置Docker中部分参数如用户信息不通过自动生成而是读取环境变量等。
>    在不需要持久卷的使用场景，环境变量更容易迁移服务器部署
>    一套helm配置文件,多个节点可以确保一致性
> 2. API接口，一旦固定，不要随意改变
>    /api/admin/storage/create
>    /api/admin/storage/update
>    这两个接口不够需要增加语义化upsert接口
>    并规范各API接口统一性
> 3. 支持并发请求三方网盘拉平tree结构，不通过缓存等直接请求对应文件。并考虑拉取速率。
> 
> And see [#74 (comment)](https://github.com/OpenListTeam/OpenList/issues/74#issuecomment-2973235964)

经过代码审查，密码功能已被加入
设置`OPENLIST_ADMIN_PASSWORD`即可设置初始密码

![Image](https://github.com/user-attachments/assets/b923e448-b932-4055-9830-672a4098f9c9)

**Comment by gowy222** [comment]
@jyxjjj 能否环境变量加一个 OPENLIST_ADMIN_TOKEN

方便使用场景如下:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alist
  namespace: default
  labels:
    Deployment: alist
spec:
  progressDeadlineSeconds: 30
  replicas: 1
  revisionHistoryLimit: 0
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: alist
  template:
    metadata:
      labels:
        Deployment: alist
        pod: alist
        app: alist
    spec:
      serviceAccountName: default
      serviceAccount: default
      terminationGracePeriodSeconds: 30
      containers:
        - name: alist
          image: "XXXXXXXXXX/alist:latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 5244
              name: alist
              protocol: TCP

          # 新增：主容器环境变量
          env:
            - name: OPENLIST_ADMIN_TOKEN
              value: "<your-token-here>"
            - name: OPENLIST_ADMIN_PASSWORD
              value: "<your-password-here>"

          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /ping
              port: 5244
              scheme: HTTP
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 3

          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /ping
              port: 5244
              scheme: HTTP
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 3

          startupProbe:
            failureThreshold: 3
            httpGet:
              path: /ping
              port: 5244
              scheme: HTTP
            periodSeconds: 80
            successThreshold: 1
            timeoutSeconds: 3

        # Sidecar容器
        - name: alist-healthcheck
          image: "XXXXXXXX/rust-alist-healthcheck:latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
              name: alist-hc-port # max 15位长度!!!
              protocol: TCP

          # 新增：Sidecar 容器环境变量, 
          ## 这里方便直接复用 OPENLIST_ADMIN_TOKEN 内部 CURL协议头直接 [Authorization]
          ### https://openlist.team/zh/guide/api/fs.html 判断三方盘探针文件存在否
          env:
            - name: OPENLIST_ADMIN_TOKEN
              value: "<your-token-here>"

          # [新增] 为sidecar容器配置其自身的健康检查探针
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /ping
              port: 9000
              scheme: HTTP
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 3

          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /ping
              port: 9000
              scheme: HTTP
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 3
            
          startupProbe:
            failureThreshold: 6 # sidecar启动快，可以更频繁地检查
            httpGet:
              path: /ping
              port: 9000
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3   

      initContainers:
        - command:
            - /mysh/ping_ocr.sh
          image: XXXXXXXXX
          imagePullPolicy: Always
          name: check-ocr

```
